config/routes.rb
# typed: strict
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  resources :home, only: [:index] do
    post :upload_file, on: :collection
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# typed: strict
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/owner.rb
# typed: strict
# frozen_string_literal: true

class Owner < ApplicationRecord
  extend T::Sig

  has_many :vehicles, dependent: :destroy

  validates :first_name, :last_name, :email, presence: { presence: true }
  validates :email, format: { with: /\A\S+@.+\.\S+\z/ }
  validates :email, uniqueness: true

  sig { returns(String) }
  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/models/vehicle.rb
# typed: strict
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  extend T::Sig

  belongs_to :owner

  validates :name, :vehicle_type, :length_in_inches, presence: true
  validates :name, uniqueness: { scope: :owner_id }

  filterrific(default_filter_params: { sorted_by: "owner_name_asc" }, available_filters: [:sorted_by])

  scope :by_owner_name, -> { includes(:owner).order("owners.last_name, owners.first_name") }
  scope :by_type, -> { order(:vehicle_type) }

  scope :sorted_by, ->(sort_option) {
    direction = /desc$/.match(sort_option) ? "desc" : "asc"

    case sort_option.to_s
    when /^owner_name_/
      includes(:owner).order("owners.last_name #{direction}, owners.first_name #{direction}")
    when /^vehicle_type_/
      order("vehicles.vehicle_type #{direction}")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  sig { returns(T::Array[T::Array[String]]) }
  def self.options_for_sorted_by
    [
      ["Owner Name ASC", "owner_name_asc"],
      ["Owner Name DESC", "owner_name_desc"],
      ["Vehicle Type ASC", "vehicle_type_asc"],
      ["Vehicle Type DESC", "vehicle_type_desc"]
    ]
  end
end

app/controllers/application_controller.rb
# typed: strict
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# typed: true
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @filterrific = init_filterrific

    @vehicles = @filterrific.find.page(params[:page]).includes(:owner).decorate
    respond_to do |format|
      format.html
      format.js
    end
  end

  def upload_file
    if upload_params[:file].present?
      Commands::FileParser.call(upload_params[:file].read)
      @vehicles = Vehicle.includes(:owner).create
      respond_to do |format|
        format.html { redirect_to root_path, notice: "File uploaded successfully" }
        format.js
      end
    else
      render json: { success: false }, status: :unprocessable_entity
    end
  end

  private def upload_params
    params.permit(:file)
  end

  private def init_filterrific
    initialize_filterrific(
      Vehicle,
      params[:filterrific],
      select_options: { sorted_by: Vehicle.options_for_sorted_by },
      persistence_id: "shared_key",
      default_filter_params: {},
      available_filters: [:sorted_by],
      ssanitize_params: true
    ) || return
  end
end

app/helpers/application_helper.rb
# typed: strict
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Outdoor.sy</h1>
<div class="row mb-2">
  <%= form_with url: upload_file_home_index_path, local: false,multipart: true, format: :js do |form| %>
    <div class="form-group mb-2">
      <%= form.label "Upload Vehicle List", class: "col-form-label" %>
      <%= form.file_field :file, required: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.submit "Upload", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<div class="row mb-4 mt-4">
<%= form_for_filterrific @filterrific, html: { id: "filterrific-no-ajax-auto-submit", class: "form-group" } do |f|%>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], class: "form-select") %>
    <%= render_filterrific_spinner %>
<%= f.submit "Filter", class: "btn btn-primary btn-sm" %>
<% end %>
<div>
<div id="vehicle-table", class="mt-3 mb-3>
  <%= render partial: "vehicles/table", locals: { vehicles: @vehicles } %>
</div>

app/views/home/upload_file.js.erb
$('#vehicle-table').html("<%= escape_javascript render(partial: 'vehicles/table', locals: {vehicles: @vehicles})") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OutdoorSy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  </head>

  <body>
    <div class='container p-5'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/vehicles/_table.html.erb
<div id="filterrific_results">
   <div class="mb-3 mb-3">
    <%= page_entries_info vehicles %>
   </div>
    <div class="table-responsive">
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th> <%=filterrific_sorting_link(@filterrific, :owner_name)%></th>
          <th>Owner Email</th>
          <th>Vehicle Name</th>
          <th><%=filterrific_sorting_link(@filterrific, :vehicle_type) %></th>
          <th>Vehicle Length</th>
          <!-- Add more headers as needed -->
        </tr>
      </thead>
      <tbody>
        <% vehicles.each do |vehicle| %>
          <tr>
            <td><%= vehicle.owner_name %></td>
            <td><%= vehicle.owner_email %></td>
            <td><%= vehicle.name %></td>
            <td><%= vehicle.vehicle_type %></td>
            <td><%= vehicle.formatted_length %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% unless vehicles.empty? %>
<%= will_paginate vehicles  %>
<%end%>